/**
 * CockpitOS — 다국어 번역 데이터
 * 모든 UI 텍스트의 4개국어(한/영/일/중) 번역
 * script.js에서 분리됨 (2026-04-08)
 */

const T = {
  ko: {
    back:'뒤로', settings:'설정', cocoName:'코코',
    p2title:'✈ CockpitOS', p2sub:'어떤 비행을 하시겠어요?',
    p2beg:'원클릭 비행', p2begD:'버튼 하나로 비행 시작! 코코가 모든 준비를 대신하고, 과정을 보여드려요.',
    p2stu:'따라하기 비행', p2stuD:'코코가 먼저 시범을 보여주고, 직접 따라하는 단계별 비행입니다.',
    p2demo:'시연 모드', p2demoD:'투자자 PT용 시연 모드입니다.',
    p3title:'원클릭 비행', p3sub:'어떻게 시작하시겠어요?',
    p3simple:'🟡 바로 날기',
    p3simpleD:'버튼 하나로 바로 하늘을 비행합니다.',
    p3edu:'🟢 배우고 날기',
    p3eduD:'코코와 함께 비행의 기초를 배웁니다.',
    cfgTitle:'✈ 비행 설정', cfgLoc:'📍 비행 지역', cfgTime:'🕐 비행 시간',
    cfgSeoul:'서울', cfgJeju:'제주', cfgDay:'주간', cfgNight:'야간',
    cfgGo:'🛫 비행 시작!',
    p32title:'📚 교육 후 비행', p32sub:'서랍을 열어서 공부하고 비행을 시작하세요',
    p4title:'훈련생 모드',
    db1:'궁금한 것', db2:'영상 보기', db3:'뭐해야 하지?', dbMic:'질문',
    greet:'저는 AI 비행 교관 코코입니다. 비행 시뮬레이션의 복잡한 조작을 버튼 하나로 해결해드리는 단축키 같은 앱입니다. 원하시는 모드를 선택해주세요.',
    flightGreet:'서울 상공에 오신 것을 환영합니다! 번호를 탭하면 제가 설명해드릴게요.',
    flightGreetJeju:'제주 상공에 오신 것을 환영합니다! 아름다운 경치를 즐기세요.',
    vbStatus:'🎤 듣고 있어요',
    vbPH:'말씀하시거나 여기를 탭해서 직접 입력하세요',
    vbAsk:'→ 코코에게 물어보기', vbDone:'마치기',
    guideTit:'📖 앱 사용 안내',
    g1t:'주먹 = 비행 멈춤', g1d:'PIP 카메라가 켜진 상태에서 주먹을 쥐면 비행이 멈춥니다.',
    g2t:'손 펼치기 = 질문', g2d:'손바닥을 펼치면 코코에게 질문할 수 있습니다.',
    g3t:'카메라로 계기 촬영', g3d:'PIP창을 열고 계기판을 비추면 코코가 설명해드립니다.',
    g4t:'되돌리기 버튼', g4d:'PIP창 안에 있습니다. 비행기를 처음 위치로 되돌립니다.',
    guideOk:'확인했습니다',
    sTTSLbl:'🔊 음성 안내', sGestLbl:'✋ 제스처 인식',
    pauseHint:'▶ 화면 터치 → 계속',
    mic:'질문',
    fiveMin:'서울 야경 어떠세요? 착륙도 해보고 싶으시면 교육 모드로 가시면 됩니다.',
    fiveMinJeju:'제주 경치 어떠세요? 더 배우고 싶으시면 교육 모드로 가시면 됩니다.',
    learnBtn:'📚 교육 받으러 가기',
    continueBtn:'✈ 계속 비행하기',
    instNames: ['속도계','자세계','고도계','방향계','선회계','승강계','마스터 SW','파킹 브레이크','스로틀','연료 밸브','혼합 조절','점화 스위치'],
    p4sub:'항공 용어와 체크리스트 중심으로 실전에 가깝게 진행합니다',
    p4preflight:'비행 전 점검 (Pre-flight)', p4preflightD:'외부 점검부터 콕핏 셋업까지 실제 체크리스트 기반으로 학습합니다.',
    p4taxi:'지상 활주 & 이륙 (Taxi & Takeoff)', p4taxiD:'ATC 교신, 활주로 진입, 이륙 절차를 단계별로 연습합니다.',
    p4cruise:'순항 & 항법 (Cruise & Navigation)', p4cruiseD:'VOR, GPS 항법과 고도/속도 유지 기법을 익힙니다.',
    p4landing:'접근 & 착륙 (Approach & Landing)', p4landingD:'ILS 접근, 시각 접근, 착륙 절차를 연습합니다.',
    p4emergency:'비상 절차 (Emergency)', p4emergencyD:'엔진 고장, 통신 두절 등 비상 상황 대응을 학습합니다.',
    p5title:'시연 모드', p5sub:'투자자 및 심사위원을 위한 PT 데모입니다',
    p5fly:'서울 상공 시연 비행', p5flyD:'계기를 탭하면 코코가 즉시 설명합니다',
    p5inst:'계기판 교육 시연', p5instD:'코코가 계기판을 하나씩 설명합니다',
    p5cam:'카메라 AI 시연', p5camD:'PIP 카메라로 계기를 촬영하면 AI가 분석합니다',
    // flight-process
    fpPreparing:'코코가 준비하고 있어요!', fpComplete:'준비 완료! 출발합니다!',
    fpBack:'← 뒤로', fpMute:'🔊 음성', fpMuted:'🔇 음소거',
    fpAsk:'🎤 코코에게 질문하기', fpSkip:'⏭ 건너뛰고 바로 비행', fpGo:'🛫 출발!',
    fpOk:'확인', fpClose:'닫기',
    fpAskTitle:'🐣 코코에게 질문하세요', fpAsking:'🐣 코코가 답변 중...',
    fpWait:'잠시만 기다려주세요...', fpAnswer:'🐣 코코의 답변',
    fpAskAgain:'다시 질문하기', fpNoApi:'API 키가 설정되지 않았어요.',
    fpInputPH:'예: 마스터 배터리가 뭐예요?', fpSend:'→ 코코에게 물어보기',
    fpAllDone:'모든 준비가 완료되었어요! 출발 버튼을 눌러주세요!',
    // flight-hud
    hudParked:'주기 중', hudReady:'엔진 가동', hudTaxi:'지상 활주',
    hudTakeoff:'이륙!', hudClimb:'상승 중', hudCruise:'순항 중',
    hudDescent:'하강 중', hudApproach:'접근 중', hudLanding:'착륙 중', hudLanded:'착륙 완료!',
    hudConnected:'Mock 모드', hudDisconnected:'연결 끊김',
    hudDemo:'시범', hudCheck:'체크', hudThrottle:'스로틀',
  },
  en: {
    back:'Back', settings:'Settings', cocoName:'Coco',
    p2title:'✈ CockpitOS', p2sub:'What flight would you like?',
    p2beg:'One-Click Flight', p2begD:'One button to fly! Coco handles everything and shows you the process.',
    p2stu:'Follow-Along Flight', p2stuD:'Coco demonstrates first, then you follow step by step.',
    p2demo:'Demo Mode', p2demoD:'Investor PT demo mode.',
    p3title:'One-Click Flight', p3sub:'How would you like to start?',
    p3simple:'🟡 Fly Now',
    p3simpleD:'One button, instant flight.',
    p3edu:'🟢 Learn & Fly',
    p3eduD:'Learn the basics with Coco.',
    cfgTitle:'✈ Flight Setup', cfgLoc:'📍 Location', cfgTime:'🕐 Time of Day',
    cfgSeoul:'Seoul', cfgJeju:'Jeju', cfgDay:'Day', cfgNight:'Night',
    cfgGo:'🛫 Start Flying!',
    p32title:'📚 Learn Then Fly', p32sub:'Open a drawer to study before flying.',
    p4title:'Student Mode',
    db1:'Find', db2:'Videos', db3:'What next?', dbMic:'Ask',
    greet:'I am Coco, your AI flight instructor. CockpitOS is like a shortcut key for flight simulators. Choose your mode to get started.',
    flightGreet:'Welcome to Seoul skies! Tap any number and I will explain.',
    flightGreetJeju:'Welcome to Jeju skies! Enjoy the beautiful scenery.',
    vbStatus:'🎤 Listening',
    vbPH:'Speak or tap here to type',
    vbAsk:'→ Ask Coco', vbDone:'Done',
    guideTit:'📖 App Guide',
    g1t:'Fist = Pause flight', g1d:'Make a fist with PIP camera on to pause.',
    g2t:'Open hand = Ask', g2d:'Open your palm to ask Coco a question.',
    g3t:'Camera scan instruments', g3d:'Open PIP and point at cockpit instruments.',
    g4t:'Reset button', g4d:'Inside PIP window. Returns aircraft to start position.',
    guideOk:'Got it',
    sTTSLbl:'🔊 Voice', sGestLbl:'✋ Gesture',
    pauseHint:'▶ Tap screen → Continue',
    mic:'Ask',
    fiveMin:'How is Seoul? If you want to land, try Learn mode!',
    fiveMinJeju:'Beautiful Jeju! Ready to learn more? Try Learn mode!',
    learnBtn:'📚 Go to Learn Mode',
    continueBtn:'✈ Keep Flying',
    instNames: ['Airspeed','Attitude','Altimeter','Heading','Turn Coord','Vert Speed','Master SW','Parking Brake','Throttle','Fuel Valve','Mixture','Ignition'],
    p4sub:'Focused on aviation terms and checklists for realistic training.',
    p4preflight:'Pre-flight Check', p4preflightD:'Learn from exterior inspection to cockpit setup with real checklists.',
    p4taxi:'Taxi & Takeoff', p4taxiD:'Practice ATC communication, runway entry, and takeoff procedures.',
    p4cruise:'Cruise & Navigation', p4cruiseD:'Learn VOR, GPS navigation and altitude/speed management.',
    p4landing:'Approach & Landing', p4landingD:'Practice ILS, visual approach, and landing procedures.',
    p4emergency:'Emergency Procedures', p4emergencyD:'Learn to handle engine failure, communication loss, and more.',
    p5title:'Demo Mode', p5sub:'PT demo for investors and evaluators',
    p5fly:'Demo Flight over Seoul', p5flyD:'Tap instruments and Coco explains instantly',
    p5inst:'Instrument Panel Demo', p5instD:'Coco explains each instrument one by one',
    p5cam:'Camera AI Demo', p5camD:'Point PIP camera at instruments for AI analysis',
    fpPreparing:'Coco is preparing!', fpComplete:'Ready! Let\'s go!',
    fpBack:'← Back', fpMute:'🔊 Voice', fpMuted:'🔇 Mute',
    fpAsk:'🎤 Ask Coco', fpSkip:'⏭ Skip to flight', fpGo:'🛫 Depart!',
    fpOk:'OK', fpClose:'Close',
    fpAskTitle:'🐣 Ask Coco a question', fpAsking:'🐣 Coco is answering...',
    fpWait:'Please wait...', fpAnswer:'🐣 Coco\'s answer',
    fpAskAgain:'Ask again', fpNoApi:'API key not set.',
    fpInputPH:'e.g. What is the master battery?', fpSend:'→ Ask Coco',
    fpAllDone:'All set! Press the depart button!',
    hudParked:'Parked', hudReady:'Engine On', hudTaxi:'Taxi',
    hudTakeoff:'Takeoff!', hudClimb:'Climbing', hudCruise:'Cruising',
    hudDescent:'Descending', hudApproach:'Approach', hudLanding:'Landing', hudLanded:'Landed!',
    hudConnected:'Mock Mode', hudDisconnected:'Disconnected',
    hudDemo:'Demo', hudCheck:'Check', hudThrottle:'Throttle',
  },
  ja: {
    back:'戻る', settings:'設定', cocoName:'ココ',
    p2title:'✈ CockpitOS', p2sub:'どんな飛行をしますか？',
    p2beg:'ワンクリック飛行', p2begD:'ボタン一つで飛行開始！ココが全て準備し、過程をお見せします。',
    p2stu:'フォローフライト', p2stuD:'ココがまず見本を見せ、あなたがステップごとに実践します。',
    p2demo:'デモモード', p2demoD:'投資家向けデモモードです。',
    p3title:'ワンクリック飛行', p3sub:'どのように始めますか？',
    p3simple:'🟡 すぐ飛ぶ',
    p3simpleD:'ボタン一つで即飛行。',
    p3edu:'🟢 学んで飛ぶ',
    p3eduD:'ここと一緒に基礎を学びます。',
    cfgTitle:'✈ 飛行設定', cfgLoc:'📍 場所', cfgTime:'🕐 時間帯',
    cfgSeoul:'ソウル', cfgJeju:'済州', cfgDay:'昼間', cfgNight:'夜間',
    cfgGo:'🛫 飛行開始！',
    p32title:'📚 学習後飛行', p32sub:'引き出しを開けて学習してから飛行しましょう',
    p4title:'訓練生モード',
    db1:'質問', db2:'動画', db3:'次は？', dbMic:'質問',
    greet:'こんにちは！ ここです。引き出しを開けて探してみてください。',
    flightGreet:'ソウルの空へようこそ！番号をタップすれば説明します。',
    flightGreetJeju:'済州の空へようこそ！美しい景色をお楽しみください。',
    vbStatus:'🎤 聞いています',
    vbPH:'話すかここをタップして入力',
    vbAsk:'→ ここに質問', vbDone:'終了',
    guideTit:'📖 アプリ使用ガイド',
    g1t:'握り拳 = 飛行停止', g1d:'PIPカメラがONの状態で握り拳を作ると停止します。',
    g2t:'手を開く = 質問', g2d:'手のひらを開くとここに質問できます。',
    g3t:'カメラで計器撮影', g3d:'PIPを開いて計器盤に向けるとここが説明します。',
    g4t:'リセットボタン', g4d:'PIPウィンドウ内にあります。',
    guideOk:'確認しました',
    sTTSLbl:'🔊 音声', sGestLbl:'✋ ジェスチャー',
    pauseHint:'▶ 画面タップ → 続ける',
    mic:'質問',
    fiveMin:'ソウルの夜景はいかがですか？着陸に挑戦するなら学習モードへ。',
    fiveMinJeju:'済州の景色はいかがですか？もっと学ぶなら学習モードへ。',
    learnBtn:'📚 学習モードへ',
    continueBtn:'✈ 飛行を続ける',
    instNames: ['速度計','姿勢計','高度計','方向計','旋回計','昇降計','マスターSW','パーキングブレーキ','スロットル','燃料バルブ','混合気','点火スイッチ'],
    p4sub:'航空用語とチェックリストで実戦的に進めます。',
    p4preflight:'飛行前点検', p4preflightD:'外部点検からコックピットセットアップまで。',
    p4taxi:'地上走行・離陸', p4taxiD:'ATC交信、滑走路進入、離陸手順を練習します。',
    p4cruise:'巡航・航法', p4cruiseD:'VOR、GPS航法と高度・速度維持を学びます。',
    p4landing:'進入・着陸', p4landingD:'ILS、視覚進入、着陸手順を練習します。',
    p4emergency:'緊急手順', p4emergencyD:'エンジン故障や通信途絶などの対応を学びます。',
    p5title:'デモモード', p5sub:'投資家向けPTデモです',
    p5fly:'ソウル上空デモ飛行', p5flyD:'計器をタップするとここが説明します',
    p5inst:'計器盤教育デモ', p5instD:'ここが計器を一つずつ説明します',
    p5cam:'カメラAIデモ', p5camD:'PIPカメラで計器を撮影するとAIが分析します',
    fpPreparing:'ここが準備しています！', fpComplete:'準備完了！出発します！',
    fpBack:'← 戻る', fpMute:'🔊 音声', fpMuted:'🔇 ミュート',
    fpAsk:'🎤 ここに質問', fpSkip:'⏭ スキップ', fpGo:'🛫 出発！',
    fpOk:'確認', fpClose:'閉じる',
    fpAskTitle:'🐣 ここに質問してください', fpAsking:'🐣 回答中...',
    fpWait:'しばらくお待ちください...', fpAnswer:'🐣 ここの回答',
    fpAskAgain:'もう一度質問', fpNoApi:'APIキーが設定されていません。',
    fpInputPH:'例：マスターバッテリーとは？', fpSend:'→ ここに質問',
    fpAllDone:'準備完了！出発ボタンを押してください！',
    hudParked:'駐機中', hudReady:'エンジン始動', hudTaxi:'地上走行',
    hudTakeoff:'離陸！', hudClimb:'上昇中', hudCruise:'巡航中',
    hudDescent:'降下中', hudApproach:'進入中', hudLanding:'着陸中', hudLanded:'着陸完了！',
    hudConnected:'Mockモード', hudDisconnected:'切断',
    hudDemo:'見本', hudCheck:'チェック', hudThrottle:'スロットル',
  },
  zh: {
    back:'返回', settings:'设置', cocoName:'可可',
    p2title:'✈ CockpitOS', p2sub:'想要什么样的飞行？',
    p2beg:'一键飞行', p2begD:'一键开始飞行！可可为您准备一切，并展示全过程。',
    p2stu:'跟随飞行', p2stuD:'可可先示范，然后您按步骤实践。',
    p2demo:'演示模式', p2demoD:'投资者演示模式。',
    p3title:'一键飞行', p3sub:'您想如何开始？',
    p3simple:'🟡 立即飞行',
    p3simpleD:'一键起飞。',
    p3edu:'🟢 学习飞行',
    p3eduD:'与可可一起学习基础。',
    cfgTitle:'✈ 飞行设置', cfgLoc:'📍 地点', cfgTime:'🕐 时间',
    cfgSeoul:'首尔', cfgJeju:'济州', cfgDay:'白天', cfgNight:'夜晚',
    cfgGo:'🛫 开始飞行！',
    p32title:'📚 学习后飞行', p32sub:'打开抽屉学习后再开始飞行',
    p4title:'学员模式',
    db1:'查找', db2:'视频', db3:'下一步？', dbMic:'提问',
    greet:'你好！我是可可。打开抽屉查找你想了解的内容。',
    flightGreet:'欢迎来到首尔上空！点击数字，我来解释。',
    flightGreetJeju:'欢迎来到济州上空！享受美丽的风景。',
    vbStatus:'🎤 正在听',
    vbPH:'说话或在此处输入',
    vbAsk:'→ 向可可提问', vbDone:'完成',
    guideTit:'📖 应用使用指南',
    g1t:'握拳 = 暂停飞行', g1d:'打开PIP摄像头后握拳即可暂停。',
    g2t:'张开手 = 提问', g2d:'张开手掌即可向可可提问。',
    g3t:'用摄像头拍摄仪表', g3d:'打开PIP并对准仪表盘，可可会解释。',
    g4t:'重置按钮', g4d:'在PIP窗口内。将飞机返回起始位置。',
    guideOk:'我知道了',
    sTTSLbl:'🔊 语音', sGestLbl:'✋ 手势',
    pauseHint:'▶ 触摸屏幕 → 继续',
    mic:'提问',
    fiveMin:'首尔夜景怎么样？想学着陆请进入学习模式！',
    fiveMinJeju:'济州风景如何？想学更多请进入学习模式！',
    learnBtn:'📚 进入学习模式',
    continueBtn:'✈ 继续飞行',
    instNames: ['空速表','姿态仪','高度表','方向仪','转弯协调','升降计','主开关','停机刹车','油门','燃油阀','混合比','点火开关'],
    p4sub:'以航空术语和检查单为主进行实战训练。',
    p4preflight:'飞行前检查', p4preflightD:'从外部检查到驾驶舱设置。',
    p4taxi:'滑行与起飞', p4taxiD:'练习ATC通信、跑道进入和起飞程序。',
    p4cruise:'巡航与导航', p4cruiseD:'学习VOR、GPS导航和高度/速度保持。',
    p4landing:'进近与着陆', p4landingD:'练习ILS进近、目视进近和着陆程序。',
    p4emergency:'紧急程序', p4emergencyD:'学习应对发动机故障、通信中断等情况。',
    p5title:'演示模式', p5sub:'面向投资者的PT演示',
    p5fly:'首尔上空演示飞行', p5flyD:'点击仪表可可立即解释',
    p5inst:'仪表盘教育演示', p5instD:'可可逐一解释仪表',
    p5cam:'摄像头AI演示', p5camD:'用PIP摄像头拍摄仪表AI分析',
    fpPreparing:'可可正在准备！', fpComplete:'准备完毕！出发吧！',
    fpBack:'← 返回', fpMute:'🔊 语音', fpMuted:'🔇 静音',
    fpAsk:'🎤 向可可提问', fpSkip:'⏭ 跳过直接飞行', fpGo:'🛫 出发！',
    fpOk:'确认', fpClose:'关闭',
    fpAskTitle:'🐣 向可可提问', fpAsking:'🐣 可可正在回答...',
    fpWait:'请稍等...', fpAnswer:'🐣 可可的回答',
    fpAskAgain:'再次提问', fpNoApi:'未设置API密钥。',
    fpInputPH:'例：什么是主电池？', fpSend:'→ 向可可提问',
    fpAllDone:'一切就绪！请按出发按钮！',
    hudParked:'停机', hudReady:'引擎启动', hudTaxi:'滑行',
    hudTakeoff:'起飞！', hudClimb:'爬升中', hudCruise:'巡航中',
    hudDescent:'下降中', hudApproach:'进近中', hudLanding:'着陆中', hudLanded:'着陆完成！',
    hudConnected:'Mock模式', hudDisconnected:'已断开',
    hudDemo:'示范', hudCheck:'检查', hudThrottle:'油门',
  },
};
