/**
 * CockpitOS — 다국어 번역 데이터
 * 모든 UI 텍스트의 4개국어(한/영/일/중) 번역
 * script.js에서 분리됨 (2026-04-08)
 */

const T = {
  ko: {
    back:'뒤로', settings:'설정', cocoName:'코코',
    p2title:'✈ CockpitOS', p2sub:'어떤 비행을 하시겠어요?',
    p2beg:'원클릭 비행', p2begD:'버튼 하나로 비행 시작! 코코가 모든 준비를 대신하고, 과정을 보여드려요.',
    p2stu:'따라하기 비행', p2stuD:'코코가 먼저 시범을 보여주고, 직접 따라하는 단계별 비행입니다.',
    p2demo:'시연 모드', p2demoD:'투자자 PT용 시연 모드입니다.',
    p3title:'원클릭 비행', p3sub:'어떻게 시작하시겠어요?',
    p3simple:'🟡 바로 날기',
    p3simpleD:'버튼 하나로 바로 하늘을 비행합니다.',
    p3edu:'🟢 배우고 날기',
    p3eduD:'코코와 함께 비행의 기초를 배웁니다.',
    cfgTitle:'✈ 비행 설정', cfgLoc:'📍 비행 지역', cfgTime:'🕐 비행 시간',
    cfgSeoul:'서울', cfgJeju:'제주', cfgDay:'주간', cfgNight:'야간',
    cfgGo:'🛫 비행 시작!',
    p32title:'📚 교육 후 비행', p32sub:'서랍을 열어서 공부하고 비행을 시작하세요',
    p4title:'훈련생 모드',
    db1:'궁금한 것', db2:'영상 보기', db3:'뭐해야 하지?', dbMic:'질문',
    greet:'저는 AI 비행 교관 코코입니다. 비행 시뮬레이션의 복잡한 조작을 버튼 하나로 해결해드리는 단축키 같은 앱입니다. 원하시는 모드를 선택해주세요.',
    flightGreet:'서울 상공에 오신 것을 환영합니다! 번호를 탭하면 제가 설명해드릴게요.',
    flightGreetJeju:'제주 상공에 오신 것을 환영합니다! 아름다운 경치를 즐기세요.',
    vbStatus:'🎤 듣고 있어요',
    vbPH:'말씀하시거나 여기를 탭해서 직접 입력하세요',
    vbAsk:'→ 코코에게 물어보기', vbDone:'마치기',
    guideTit:'📖 앱 사용 안내',
    g1t:'주먹 = 비행 멈춤', g1d:'PIP 카메라가 켜진 상태에서 주먹을 쥐면 비행이 멈춥니다.',
    g2t:'손 펼치기 = 질문', g2d:'손바닥을 펼치면 코코에게 질문할 수 있습니다.',
    g3t:'카메라로 계기 촬영', g3d:'PIP창을 열고 계기판을 비추면 코코가 설명해드립니다.',
    g4t:'되돌리기 버튼', g4d:'PIP창 안에 있습니다. 비행기를 처음 위치로 되돌립니다.',
    guideOk:'확인했습니다',
    sTTSLbl:'🔊 음성 안내', sGestLbl:'✋ 제스처 인식',
    pauseHint:'▶ 화면 터치 → 계속',
    mic:'질문',
    fiveMin:'서울 야경 어떠세요? 착륙도 해보고 싶으시면 교육 모드로 가시면 됩니다.',
    fiveMinJeju:'제주 경치 어떠세요? 더 배우고 싶으시면 교육 모드로 가시면 됩니다.',
    learnBtn:'📚 교육 받으러 가기',
    continueBtn:'✈ 계속 비행하기',
    instNames: ['속도계','자세계','고도계','방향계','선회계','승강계','마스터 SW','파킹 브레이크','스로틀','연료 밸브','혼합 조절','점화 스위치'],
    p4sub:'항공 용어와 체크리스트 중심으로 실전에 가깝게 진행합니다',
    p4preflight:'비행 전 점검 (Pre-flight)', p4preflightD:'외부 점검부터 콕핏 셋업까지 실제 체크리스트 기반으로 학습합니다.',
    p4taxi:'지상 활주 & 이륙 (Taxi & Takeoff)', p4taxiD:'ATC 교신, 활주로 진입, 이륙 절차를 단계별로 연습합니다.',
    p4cruise:'순항 & 항법 (Cruise & Navigation)', p4cruiseD:'VOR, GPS 항법과 고도/속도 유지 기법을 익힙니다.',
    p4landing:'접근 & 착륙 (Approach & Landing)', p4landingD:'ILS 접근, 시각 접근, 착륙 절차를 연습합니다.',
    p4emergency:'비상 절차 (Emergency)', p4emergencyD:'엔진 고장, 통신 두절 등 비상 상황 대응을 학습합니다.',
    p5title:'시연 모드', p5sub:'투자자 및 심사위원을 위한 PT 데모입니다',
    p5fly:'서울 상공 시연 비행', p5flyD:'계기를 탭하면 코코가 즉시 설명합니다',
    p5inst:'계기판 교육 시연', p5instD:'코코가 계기판을 하나씩 설명합니다',
    p5cam:'카메라 AI 시연', p5camD:'PIP 카메라로 계기를 촬영하면 AI가 분석합니다',
    // flight-process
    fpPreparing:'코코가 준비하고 있어요!', fpComplete:'준비 완료! 출발합니다!',
    fpBack:'← 뒤로', fpMute:'🔊 음성', fpMuted:'🔇 음소거',
    fpAsk:'🎤 코코에게 질문하기', fpSkip:'⏭ 건너뛰고 바로 비행', fpGo:'🛫 출발!',
    fpOk:'확인', fpClose:'닫기',
    fpAskTitle:'🐣 코코에게 질문하세요', fpAsking:'🐣 코코가 답변 중...',
    fpWait:'잠시만 기다려주세요...', fpAnswer:'🐣 코코의 답변',
    fpAskAgain:'다시 질문하기', fpNoApi:'API 키가 설정되지 않았어요.',
    fpInputPH:'예: 마스터 배터리가 뭐예요?', fpSend:'→ 코코에게 물어보기',
    fpAllDone:'모든 준비가 완료되었어요! 출발 버튼을 눌러주세요!',
    // flight-hud
    hudParked:'주기 중', hudReady:'엔진 가동', hudTaxi:'지상 활주',
    hudTakeoff:'이륙!', hudClimb:'상승 중', hudCruise:'순항 중',
    hudDescent:'하강 중', hudApproach:'접근 중', hudLanding:'착륙 중', hudLanded:'착륙 완료!',
    hudConnected:'Mock 모드', hudDisconnected:'연결 끊김',
    hudDemo:'시범', hudCheck:'체크', hudThrottle:'스로틀',
    // 비행 단계별 코칭 메시지
    coachParked:'🅿️ 주기 중이에요. 준비되면 스로틀을 올려 활주로로 이동하세요.',
    coachReady:'🔑 엔진이 돌고 있어요! 파킹 브레이크를 풀고 활주를 시작하세요.',
    coachTaxi:'🚕 지상 활주 중. 천천히 활주로 끝으로 이동하세요.',
    coachTakeoff:'🛫 이륙! 스로틀 풀파워, 속도 55kt에서 기수를 살짝 들어주세요!',
    coachClimb:'📈 상승 중. 고도 3000ft까지 올려주세요. 잘하고 있어요!',
    coachCruise:'✈️ 순항 중. 고도와 속도를 유지하세요. 관광을 즐기세요!',
    coachDescent:'📉 하강 시작. 속도를 줄이고 고도를 낮추세요.',
    coachApproach:'🛬 접근 중. 플랩 내리고 속도 90kt로 유지하세요.',
    coachLanding:'🎯 착륙 중! 기수 살짝 들고 부드럽게 내려주세요.',
    coachLanded:'✅ 착륙 완료! 수고하셨어요. 멋진 비행이었습니다!',
  },
  en: {
    back:'Back', settings:'Settings', cocoName:'Coco',
    p2title:'✈ CockpitOS', p2sub:'What flight would you like?',
    p2beg:'One-Click Flight', p2begD:'One button to fly! Coco handles everything and shows you the process.',
    p2stu:'Follow-Along Flight', p2stuD:'Coco demonstrates first, then you follow step by step.',
    p2demo:'Demo Mode', p2demoD:'Investor PT demo mode.',
    p3title:'One-Click Flight', p3sub:'How would you like to start?',
    p3simple:'🟡 Fly Now',
    p3simpleD:'One button, instant flight.',
    p3edu:'🟢 Learn & Fly',
    p3eduD:'Learn the basics with Coco.',
    cfgTitle:'✈ Flight Setup', cfgLoc:'📍 Location', cfgTime:'🕐 Time of Day',
    cfgSeoul:'Seoul', cfgJeju:'Jeju', cfgDay:'Day', cfgNight:'Night',
    cfgGo:'🛫 Start Flying!',
    p32title:'📚 Learn Then Fly', p32sub:'Open a drawer to study before flying.',
    p4title:'Student Mode',
    db1:'Find', db2:'Videos', db3:'What next?', dbMic:'Ask',
    greet:'I am Coco, your AI flight instructor. CockpitOS is like a shortcut key for flight simulators. Choose your mode to get started.',
    flightGreet:'Welcome to Seoul skies! Tap any number and I will explain.',
    flightGreetJeju:'Welcome to Jeju skies! Enjoy the beautiful scenery.',
    vbStatus:'🎤 Listening',
    vbPH:'Speak or tap here to type',
    vbAsk:'→ Ask Coco', vbDone:'Done',
    guideTit:'📖 App Guide',
    g1t:'Fist = Pause flight', g1d:'Make a fist with PIP camera on to pause.',
    g2t:'Open hand = Ask', g2d:'Open your palm to ask Coco a question.',
    g3t:'Camera scan instruments', g3d:'Open PIP and point at cockpit instruments.',
    g4t:'Reset button', g4d:'Inside PIP window. Returns aircraft to start position.',
    guideOk:'Got it',
    sTTSLbl:'🔊 Voice', sGestLbl:'✋ Gesture',
    pauseHint:'▶ Tap screen → Continue',
    mic:'Ask',
    fiveMin:'How is Seoul? If you want to land, try Learn mode!',
    fiveMinJeju:'Beautiful Jeju! Ready to learn more? Try Learn mode!',
    learnBtn:'📚 Go to Learn Mode',
    continueBtn:'✈ Keep Flying',
    instNames: ['Airspeed','Attitude','Altimeter','Heading','Turn Coord','Vert Speed','Master SW','Parking Brake','Throttle','Fuel Valve','Mixture','Ignition'],
    p4sub:'Focused on aviation terms and checklists for realistic training.',
    p4preflight:'Pre-flight Check', p4preflightD:'Learn from exterior inspection to cockpit setup with real checklists.',
    p4taxi:'Taxi & Takeoff', p4taxiD:'Practice ATC communication, runway entry, and takeoff procedures.',
    p4cruise:'Cruise & Navigation', p4cruiseD:'Learn VOR, GPS navigation and altitude/speed management.',
    p4landing:'Approach & Landing', p4landingD:'Practice ILS, visual approach, and landing procedures.',
    p4emergency:'Emergency Procedures', p4emergencyD:'Learn to handle engine failure, communication loss, and more.',
    p5title:'Demo Mode', p5sub:'PT demo for investors and evaluators',
    p5fly:'Demo Flight over Seoul', p5flyD:'Tap instruments and Coco explains instantly',
    p5inst:'Instrument Panel Demo', p5instD:'Coco explains each instrument one by one',
    p5cam:'Camera AI Demo', p5camD:'Point PIP camera at instruments for AI analysis',
    fpPreparing:'Coco is preparing!', fpComplete:'Ready! Let\'s go!',
    fpBack:'← Back', fpMute:'🔊 Voice', fpMuted:'🔇 Mute',
    fpAsk:'🎤 Ask Coco', fpSkip:'⏭ Skip to flight', fpGo:'🛫 Depart!',
    fpOk:'OK', fpClose:'Close',
    fpAskTitle:'🐣 Ask Coco a question', fpAsking:'🐣 Coco is answering...',
    fpWait:'Please wait...', fpAnswer:'🐣 Coco\'s answer',
    fpAskAgain:'Ask again', fpNoApi:'API key not set.',
    fpInputPH:'e.g. What is the master battery?', fpSend:'→ Ask Coco',
    fpAllDone:'All set! Press the depart button!',
    hudParked:'Parked', hudReady:'Engine On', hudTaxi:'Taxi',
    hudTakeoff:'Takeoff!', hudClimb:'Climbing', hudCruise:'Cruising',
    hudDescent:'Descending', hudApproach:'Approach', hudLanding:'Landing', hudLanded:'Landed!',
    hudConnected:'Mock Mode', hudDisconnected:'Disconnected',
    hudDemo:'Demo', hudCheck:'Check', hudThrottle:'Throttle',
    coachParked:'🅿️ Parked. When ready, advance throttle and taxi to runway.',
    coachReady:'🔑 Engine running! Release parking brake and start taxiing.',
    coachTaxi:'🚕 Taxiing. Slowly proceed to runway end.',
    coachTakeoff:'🛫 Takeoff! Full throttle, rotate at 55kt!',
    coachClimb:'📈 Climbing. Target altitude 3000ft. Great job!',
    coachCruise:'✈️ Cruising. Maintain altitude and speed. Enjoy the view!',
    coachDescent:'📉 Descending. Reduce speed and altitude.',
    coachApproach:'🛬 On approach. Flaps down, maintain 90kt.',
    coachLanding:'🎯 Landing! Slight nose-up, smooth touchdown.',
    coachLanded:'✅ Landed! Great flight, well done!',
  },
  ja: {
    back:'戻る', settings:'設定', cocoName:'ココ',
    p2title:'✈ CockpitOS', p2sub:'どんな飛行をしますか？',
    p2beg:'ワンクリック飛行', p2begD:'ボタン一つで飛行開始！ココが全て準備し、過程をお見せします。',
    p2stu:'フォローフライト', p2stuD:'ココがまず見本を見せ、あなたがステップごとに実践します。',
    p2demo:'デモモード', p2demoD:'投資家向けデモモードです。',
    p3title:'ワンクリック飛行', p3sub:'どのように始めますか？',
    p3simple:'🟡 すぐ飛ぶ',
    p3simpleD:'ボタン一つで即飛行。',
    p3edu:'🟢 学んで飛ぶ',
    p3eduD:'ここと一緒に基礎を学びます。',
    cfgTitle:'✈ 飛行設定', cfgLoc:'📍 場所', cfgTime:'🕐 時間帯',
    cfgSeoul:'ソウル', cfgJeju:'済州', cfgDay:'昼間', cfgNight:'夜間',
    cfgGo:'🛫 飛行開始！',
    p32title:'📚 学習後飛行', p32sub:'引き出しを開けて学習してから飛行しましょう',
    p4title:'訓練生モード',
    db1:'質問', db2:'動画', db3:'次は？', dbMic:'質問',
    greet:'こんにちは！ ここです。引き出しを開けて探してみてください。',
    flightGreet:'ソウルの空へようこそ！番号をタップすれば説明します。',
    flightGreetJeju:'済州の空へようこそ！美しい景色をお楽しみください。',
    vbStatus:'🎤 聞いています',
    vbPH:'話すかここをタップして入力',
    vbAsk:'→ ここに質問', vbDone:'終了',
    guideTit:'📖 アプリ使用ガイド',
    g1t:'握り拳 = 飛行停止', g1d:'PIPカメラがONの状態で握り拳を作ると停止します。',
    g2t:'手を開く = 質問', g2d:'手のひらを開くとここに質問できます。',
    g3t:'カメラで計器撮影', g3d:'PIPを開いて計器盤に向けるとここが説明します。',
    g4t:'リセットボタン', g4d:'PIPウィンドウ内にあります。',
    guideOk:'確認しました',
    sTTSLbl:'🔊 音声', sGestLbl:'✋ ジェスチャー',
    pauseHint:'▶ 画面タップ → 続ける',
    mic:'質問',
    fiveMin:'ソウルの夜景はいかがですか？着陸に挑戦するなら学習モードへ。',
    fiveMinJeju:'済州の景色はいかがですか？もっと学ぶなら学習モードへ。',
    learnBtn:'📚 学習モードへ',
    continueBtn:'✈ 飛行を続ける',
    instNames: ['速度計','姿勢計','高度計','方向計','旋回計','昇降計','マスターSW','パーキングブレーキ','スロットル','燃料バルブ','混合気','点火スイッチ'],
    p4sub:'航空用語とチェックリストで実戦的に進めます。',
    p4preflight:'飛行前点検', p4preflightD:'外部点検からコックピットセットアップまで。',
    p4taxi:'地上走行・離陸', p4taxiD:'ATC交信、滑走路進入、離陸手順を練習します。',
    p4cruise:'巡航・航法', p4cruiseD:'VOR、GPS航法と高度・速度維持を学びます。',
    p4landing:'進入・着陸', p4landingD:'ILS、視覚進入、着陸手順を練習します。',
    p4emergency:'緊急手順', p4emergencyD:'エンジン故障や通信途絶などの対応を学びます。',
    p5title:'デモモード', p5sub:'投資家向けPTデモです',
    p5fly:'ソウル上空デモ飛行', p5flyD:'計器をタップするとここが説明します',
    p5inst:'計器盤教育デモ', p5instD:'ここが計器を一つずつ説明します',
    p5cam:'カメラAIデモ', p5camD:'PIPカメラで計器を撮影するとAIが分析します',
    fpPreparing:'ここが準備しています！', fpComplete:'準備完了！出発します！',
    fpBack:'← 戻る', fpMute:'🔊 音声', fpMuted:'🔇 ミュート',
    fpAsk:'🎤 ここに質問', fpSkip:'⏭ スキップ', fpGo:'🛫 出発！',
    fpOk:'確認', fpClose:'閉じる',
    fpAskTitle:'🐣 ここに質問してください', fpAsking:'🐣 回答中...',
    fpWait:'しばらくお待ちください...', fpAnswer:'🐣 ここの回答',
    fpAskAgain:'もう一度質問', fpNoApi:'APIキーが設定されていません。',
    fpInputPH:'例：マスターバッテリーとは？', fpSend:'→ ここに質問',
    fpAllDone:'準備完了！出発ボタンを押してください！',
    hudParked:'駐機中', hudReady:'エンジン始動', hudTaxi:'地上走行',
    hudTakeoff:'離陸！', hudClimb:'上昇中', hudCruise:'巡航中',
    hudDescent:'降下中', hudApproach:'進入中', hudLanding:'着陸中', hudLanded:'着陸完了！',
    hudConnected:'Mockモード', hudDisconnected:'切断',
    hudDemo:'見本', hudCheck:'チェック', hudThrottle:'スロットル',
    coachParked:'🅿️ 駐機中。準備ができたらスロットルを上げて滑走路へ。',
    coachReady:'🔑 エンジン始動！パーキングブレーキを外して走行開始。',
    coachTaxi:'🚕 地上走行中。ゆっくり滑走路の端へ。',
    coachTakeoff:'🛫 離陸！フルスロットル、55ktで機首を上げて！',
    coachClimb:'📈 上昇中。目標高度3000ftまで。素晴らしい！',
    coachCruise:'✈️ 巡航中。高度と速度を維持。景色をお楽しみください！',
    coachDescent:'📉 降下開始。速度と高度を下げてください。',
    coachApproach:'🛬 進入中。フラップ下げ、90kt維持。',
    coachLanding:'🎯 着陸中！機首少し上げて、滑らかに着地。',
    coachLanded:'✅ 着陸完了！素晴らしい飛行でした！',
  },
  zh: {
    back:'返回', settings:'设置', cocoName:'可可',
    p2title:'✈ CockpitOS', p2sub:'想要什么样的飞行？',
    p2beg:'一键飞行', p2begD:'一键开始飞行！可可为您准备一切，并展示全过程。',
    p2stu:'跟随飞行', p2stuD:'可可先示范，然后您按步骤实践。',
    p2demo:'演示模式', p2demoD:'投资者演示模式。',
    p3title:'一键飞行', p3sub:'您想如何开始？',
    p3simple:'🟡 立即飞行',
    p3simpleD:'一键起飞。',
    p3edu:'🟢 学习飞行',
    p3eduD:'与可可一起学习基础。',
    cfgTitle:'✈ 飞行设置', cfgLoc:'📍 地点', cfgTime:'🕐 时间',
    cfgSeoul:'首尔', cfgJeju:'济州', cfgDay:'白天', cfgNight:'夜晚',
    cfgGo:'🛫 开始飞行！',
    p32title:'📚 学习后飞行', p32sub:'打开抽屉学习后再开始飞行',
    p4title:'学员模式',
    db1:'查找', db2:'视频', db3:'下一步？', dbMic:'提问',
    greet:'你好！我是可可。打开抽屉查找你想了解的内容。',
    flightGreet:'欢迎来到首尔上空！点击数字，我来解释。',
    flightGreetJeju:'欢迎来到济州上空！享受美丽的风景。',
    vbStatus:'🎤 正在听',
    vbPH:'说话或在此处输入',
    vbAsk:'→ 向可可提问', vbDone:'完成',
    guideTit:'📖 应用使用指南',
    g1t:'握拳 = 暂停飞行', g1d:'打开PIP摄像头后握拳即可暂停。',
    g2t:'张开手 = 提问', g2d:'张开手掌即可向可可提问。',
    g3t:'用摄像头拍摄仪表', g3d:'打开PIP并对准仪表盘，可可会解释。',
    g4t:'重置按钮', g4d:'在PIP窗口内。将飞机返回起始位置。',
    guideOk:'我知道了',
    sTTSLbl:'🔊 语音', sGestLbl:'✋ 手势',
    pauseHint:'▶ 触摸屏幕 → 继续',
    mic:'提问',
    fiveMin:'首尔夜景怎么样？想学着陆请进入学习模式！',
    fiveMinJeju:'济州风景如何？想学更多请进入学习模式！',
    learnBtn:'📚 进入学习模式',
    continueBtn:'✈ 继续飞行',
    instNames: ['空速表','姿态仪','高度表','方向仪','转弯协调','升降计','主开关','停机刹车','油门','燃油阀','混合比','点火开关'],
    p4sub:'以航空术语和检查单为主进行实战训练。',
    p4preflight:'飞行前检查', p4preflightD:'从外部检查到驾驶舱设置。',
    p4taxi:'滑行与起飞', p4taxiD:'练习ATC通信、跑道进入和起飞程序。',
    p4cruise:'巡航与导航', p4cruiseD:'学习VOR、GPS导航和高度/速度保持。',
    p4landing:'进近与着陆', p4landingD:'练习ILS进近、目视进近和着陆程序。',
    p4emergency:'紧急程序', p4emergencyD:'学习应对发动机故障、通信中断等情况。',
    p5title:'演示模式', p5sub:'面向投资者的PT演示',
    p5fly:'首尔上空演示飞行', p5flyD:'点击仪表可可立即解释',
    p5inst:'仪表盘教育演示', p5instD:'可可逐一解释仪表',
    p5cam:'摄像头AI演示', p5camD:'用PIP摄像头拍摄仪表AI分析',
    fpPreparing:'可可正在准备！', fpComplete:'准备完毕！出发吧！',
    fpBack:'← 返回', fpMute:'🔊 语音', fpMuted:'🔇 静音',
    fpAsk:'🎤 向可可提问', fpSkip:'⏭ 跳过直接飞行', fpGo:'🛫 出发！',
    fpOk:'确认', fpClose:'关闭',
    fpAskTitle:'🐣 向可可提问', fpAsking:'🐣 可可正在回答...',
    fpWait:'请稍等...', fpAnswer:'🐣 可可的回答',
    fpAskAgain:'再次提问', fpNoApi:'未设置API密钥。',
    fpInputPH:'例：什么是主电池？', fpSend:'→ 向可可提问',
    fpAllDone:'一切就绪！请按出发按钮！',
    hudParked:'停机', hudReady:'引擎启动', hudTaxi:'滑行',
    hudTakeoff:'起飞！', hudClimb:'爬升中', hudCruise:'巡航中',
    hudDescent:'下降中', hudApproach:'进近中', hudLanding:'着陆中', hudLanded:'着陆完成！',
    hudConnected:'Mock模式', hudDisconnected:'已断开',
    hudDemo:'示范', hudCheck:'检查', hudThrottle:'油门',
    coachParked:'🅿️ 停机中。准备好后推油门滑行到跑道。',
    coachReady:'🔑 引擎启动！松开驻机刹车开始滑行。',
    coachTaxi:'🚕 滑行中。缓慢移动到跑道尽头。',
    coachTakeoff:'🛫 起飞！油门全开，55节时拉起机头！',
    coachClimb:'📈 爬升中。目标高度3000英尺。做得好！',
    coachCruise:'✈️ 巡航中。保持高度和速度。享受风景！',
    coachDescent:'📉 开始下降。降低速度和高度。',
    coachApproach:'🛬 进近中。放下襟翼，保持90节。',
    coachLanding:'🎯 着陆中！机头略抬起，平稳接地。',
    coachLanded:'✅ 着陆完成！飞行很棒，辛苦了！',
  },
};

// ── 비행 준비 단계 다국어 데이터 ──
const STEPS_I18N = {
  seoul_tour: {
    ko: [
      {label:'김포공항 선택', detail:'김포국제공항(RKSS)은 서울 서쪽에 있는 공항이에요. 국내선과 일부 국제선이 운항합니다.', voice:'김포공항을 선택합니다.'},
      {label:'Cessna 172 배치', detail:'Cessna 172는 세계에서 가장 많이 쓰이는 훈련용 비행기예요. 초보자에게 가장 좋습니다.', voice:'세스나 172를 배치합니다.'},
      {label:'활주로 32L 이동', detail:'활주로 32L은 방향 321도를 뜻해요. L은 왼쪽(Left)입니다.', voice:'활주로 32 레프트로 이동합니다.'},
      {label:'날씨 확인 (맑음)', detail:'METAR라는 항공 기상 정보를 확인합니다. 오늘은 맑고 바람이 약해서 비행하기 좋아요!', voice:'날씨를 확인합니다. 오늘은 맑아요!'},
      {label:'마스터 배터리 ON', detail:'비행기의 전원을 켜는 첫 단계예요. 자동차의 시동키를 ACC에 돌리는 것과 같아요.', voice:'마스터 배터리를 켭니다.'},
      {label:'아비오닉스 ON', detail:'아비오닉스는 항공 전자장비를 뜻해요. 이걸 켜야 계기판에 불이 들어옵니다.', voice:'아비오닉스를 켭니다.'},
      {label:'비컨 라이트 ON', detail:'비컨은 빨간 회전 경고등이에요. "엔진을 켤 거니까 가까이 오지 마세요"라는 신호입니다.', voice:'비컨 라이트를 켭니다.'},
      {label:'엔진 시동', detail:'프로펠러가 돌아가기 시작해요! 코코가 한번에 해드려요.', voice:'엔진 시동을 겁니다.'},
      {label:'NAV/스트로브 라이트 ON', detail:'NAV 라이트는 왼쪽 빨강, 오른쪽 초록이에요. 다른 비행기가 내 방향을 알 수 있어요.', voice:'항법 라이트를 켭니다.'},
      {label:'플랩 10° 설정', detail:'플랩은 날개 뒤쪽의 판이에요. 펼치면 양력이 커져서 낮은 속도에서도 뜰 수 있어요.', voice:'플랩을 10도로 설정합니다.'},
      {label:'파킹 브레이크 해제', detail:'주차 브레이크를 풀어야 움직일 수 있어요.', voice:'파킹 브레이크를 해제합니다.'},
      {label:'이륙 준비 완료!', detail:'모든 준비가 끝났어요! 스로틀을 올리면 비행기가 달리기 시작합니다.', voice:'이륙 준비가 완료되었습니다!'},
    ],
    en: [
      {label:'Select Gimpo Airport', detail:'Gimpo International Airport (RKSS) is located west of Seoul. It serves domestic and some international flights.', voice:'Selecting Gimpo Airport.'},
      {label:'Place Cessna 172', detail:'The Cessna 172 is the most widely used training aircraft in the world. Perfect for beginners.', voice:'Placing Cessna 172.'},
      {label:'Move to Runway 32L', detail:'Runway 32L means heading 321 degrees. L stands for Left.', voice:'Moving to runway 32 Left.'},
      {label:'Check Weather (Clear)', detail:'Checking METAR aviation weather info. Today is clear with light winds — great for flying!', voice:'Checking weather. Clear skies today!'},
      {label:'Master Battery ON', detail:'First step to power up the aircraft. Like turning the car key to ACC.', voice:'Turning on master battery.'},
      {label:'Avionics ON', detail:'Avionics means aviation electronics. This powers up all the instruments.', voice:'Turning on avionics.'},
      {label:'Beacon Light ON', detail:'The beacon is a red rotating light. It signals "Engine starting, stay clear!"', voice:'Turning on beacon light.'},
      {label:'Engine Start', detail:'The propeller starts spinning! Coco handles everything for you.', voice:'Starting the engine.'},
      {label:'NAV/Strobe Lights ON', detail:'NAV lights: red on left, green on right. Other aircraft can see your direction.', voice:'Turning on navigation lights.'},
      {label:'Flaps 10°', detail:'Flaps are panels on the wing. Extended, they create more lift for takeoff.', voice:'Setting flaps to 10 degrees.'},
      {label:'Release Parking Brake', detail:'Release the parking brake to start moving.', voice:'Releasing parking brake.'},
      {label:'Ready for Takeoff!', detail:'All set! Push the throttle and the aircraft starts rolling.', voice:'Ready for takeoff!'},
    ],
    ja: [
      {label:'金浦空港を選択', detail:'金浦国際空港(RKSS)はソウル西側の空港です。国内線と一部の国際線が就航しています。', voice:'金浦空港を選択します。'},
      {label:'Cessna 172を配置', detail:'Cessna 172は世界で最も使われている訓練機です。初心者に最適です。', voice:'セスナ172を配置します。'},
      {label:'滑走路32Lへ移動', detail:'滑走路32Lは方向321度を意味します。Lは左(Left)です。', voice:'滑走路32レフトへ移動します。'},
      {label:'天候確認（晴れ）', detail:'METAR航空気象情報を確認します。今日は晴れで風も弱く、飛行日和です！', voice:'天候を確認します。今日は晴れです！'},
      {label:'マスターバッテリーON', detail:'航空機の電源を入れる最初のステップです。', voice:'マスターバッテリーをONにします。'},
      {label:'アビオニクスON', detail:'アビオニクスは航空電子機器です。これでコックピットに電力が供給されます。', voice:'アビオニクスをONにします。'},
      {label:'ビーコンライトON', detail:'ビーコンは赤い回転灯です。「エンジン始動中、近づかないで」というサインです。', voice:'ビーコンライトをONにします。'},
      {label:'エンジン始動', detail:'プロペラが回り始めます！ここが全て処理します。', voice:'エンジンを始動します。'},
      {label:'NAV/ストロボライトON', detail:'NAVライトは左が赤、右が緑。他の航空機があなたの方向を知ることができます。', voice:'航法ライトをONにします。'},
      {label:'フラップ10°', detail:'フラップは翼の後ろの板です。展開すると揚力が増します。', voice:'フラップを10度に設定します。'},
      {label:'パーキングブレーキ解除', detail:'駐機ブレーキを解除して動き出せるようにします。', voice:'パーキングブレーキを解除します。'},
      {label:'離陸準備完了！', detail:'全ての準備が完了しました！スロットルを上げると走り出します。', voice:'離陸準備が完了しました！'},
    ],
    zh: [
      {label:'选择金浦机场', detail:'金浦国际机场(RKSS)位于首尔西侧，运营国内和部分国际航线。', voice:'选择金浦机场。'},
      {label:'放置Cessna 172', detail:'Cessna 172是世界上使用最广泛的训练飞机，最适合初学者。', voice:'放置Cessna 172。'},
      {label:'移至跑道32L', detail:'跑道32L表示方向321度。L代表左侧(Left)。', voice:'移至跑道32左。'},
      {label:'确认天气（晴）', detail:'查看METAR航空气象信息。今天晴朗，微风，非常适合飞行！', voice:'确认天气。今天是晴天！'},
      {label:'主电池开', detail:'给飞机通电的第一步，就像把车钥匙转到ACC位置。', voice:'打开主电池。'},
      {label:'航电设备开', detail:'航电设备是航空电子装置，打开后仪表盘才会亮起。', voice:'打开航电设备。'},
      {label:'信标灯开', detail:'信标是红色旋转警告灯，表示"即将启动发动机，请远离"。', voice:'打开信标灯。'},
      {label:'启动发动机', detail:'螺旋桨开始转动！可可为您一键处理。', voice:'启动发动机。'},
      {label:'NAV/频闪灯开', detail:'NAV灯左红右绿，其他飞机可以知道您的方向。', voice:'打开导航灯。'},
      {label:'襟翼10°', detail:'襟翼是机翼后方的板，展开后增加升力。', voice:'设置襟翼10度。'},
      {label:'松开驻机刹车', detail:'松开驻机刹车才能移动。', voice:'松开驻机刹车。'},
      {label:'准备起飞！', detail:'一切就绪！推油门飞机就开始滑行。', voice:'起飞准备完毕！'},
    ],
  },
  jeju_tour: {
    ko: [
      {label:'제주공항 선택', detail:'제주국제공항(RKPC)은 대한민국에서 가장 붐비는 공항 중 하나예요.', voice:'제주공항을 선택합니다.'},
      {label:'Cessna 172 배치', detail:'Cessna 172는 세계에서 가장 많이 쓰이는 훈련용 비행기예요.', voice:'세스나 172를 배치합니다.'},
      {label:'활주로 07 이동', detail:'활주로 07은 방향 73도(동쪽)를 뜻해요. 제주공항의 주요 활주로입니다.', voice:'활주로 07로 이동합니다.'},
      {label:'날씨 확인 (맑음)', detail:'제주는 바람이 조금 있지만 비행하기 좋은 날씨에요!', voice:'날씨를 확인합니다.'},
      {label:'마스터 배터리 ON', detail:'비행기의 전원을 켜는 첫 단계예요.', voice:'마스터 배터리를 켭니다.'},
      {label:'아비오닉스 ON', detail:'항공 전자장비를 켭니다.', voice:'아비오닉스를 켭니다.'},
      {label:'비컨 라이트 ON', detail:'빨간 회전 경고등을 켭니다.', voice:'비컨 라이트를 켭니다.'},
      {label:'엔진 시동', detail:'프로펠러가 돌아가기 시작합니다!', voice:'엔진 시동을 겁니다.'},
      {label:'NAV/스트로브 라이트 ON', detail:'항법등을 켭니다.', voice:'항법 라이트를 켭니다.'},
      {label:'플랩 10° 설정', detail:'이륙을 위해 플랩을 펼칩니다.', voice:'플랩을 10도로 설정합니다.'},
      {label:'파킹 브레이크 해제', detail:'주차 브레이크를 풉니다.', voice:'파킹 브레이크를 해제합니다.'},
      {label:'이륙 준비 완료!', detail:'모든 준비가 끝났어요! 아름다운 제주 하늘로 출발합니다!', voice:'이륙 준비 완료!'},
    ],
    en: [
      {label:'Select Jeju Airport', detail:'Jeju International Airport (RKPC) is one of the busiest airports in South Korea.', voice:'Selecting Jeju Airport.'},
      {label:'Place Cessna 172', detail:'The Cessna 172 is the most popular training aircraft worldwide.', voice:'Placing Cessna 172.'},
      {label:'Move to Runway 07', detail:'Runway 07 means heading 73 degrees (east). The main runway at Jeju.', voice:'Moving to runway 07.'},
      {label:'Check Weather (Clear)', detail:'Jeju has some wind but great flying weather today!', voice:'Checking weather.'},
      {label:'Master Battery ON', detail:'First step to power up the aircraft.', voice:'Master battery on.'},
      {label:'Avionics ON', detail:'Powering up aviation electronics.', voice:'Avionics on.'},
      {label:'Beacon Light ON', detail:'Turning on the red rotating beacon.', voice:'Beacon light on.'},
      {label:'Engine Start', detail:'The propeller starts spinning!', voice:'Starting engine.'},
      {label:'NAV/Strobe Lights ON', detail:'Navigation lights on.', voice:'Navigation lights on.'},
      {label:'Flaps 10°', detail:'Extending flaps for takeoff.', voice:'Flaps set to 10 degrees.'},
      {label:'Release Parking Brake', detail:'Releasing parking brake.', voice:'Parking brake released.'},
      {label:'Ready for Takeoff!', detail:'All set! Off to the beautiful Jeju skies!', voice:'Ready for takeoff!'},
    ],
    ja: [
      {label:'済州空港を選択', detail:'済州国際空港(RKPC)は韓国で最も忙しい空港の一つです。', voice:'済州空港を選択します。'},
      {label:'Cessna 172を配置', detail:'世界で最も使われている訓練機です。', voice:'セスナ172を配置します。'},
      {label:'滑走路07へ移動', detail:'滑走路07は方向73度（東）。済州空港のメイン滑走路です。', voice:'滑走路07へ移動します。'},
      {label:'天候確認（晴れ）', detail:'済州は少し風がありますが飛行日和です！', voice:'天候を確認します。'},
      {label:'マスターバッテリーON', detail:'航空機の電源を入れます。', voice:'マスターバッテリーON。'},
      {label:'アビオニクスON', detail:'航空電子機器をONにします。', voice:'アビオニクスON。'},
      {label:'ビーコンライトON', detail:'赤い回転灯をONにします。', voice:'ビーコンライトON。'},
      {label:'エンジン始動', detail:'プロペラが回り始めます！', voice:'エンジン始動。'},
      {label:'NAV/ストロボライトON', detail:'航法ライトをONにします。', voice:'航法ライトON。'},
      {label:'フラップ10°', detail:'離陸のためフラップを展開します。', voice:'フラップ10度。'},
      {label:'パーキングブレーキ解除', detail:'駐機ブレーキを解除します。', voice:'ブレーキ解除。'},
      {label:'離陸準備完了！', detail:'全て完了！美しい済州の空へ出発します！', voice:'離陸準備完了！'},
    ],
    zh: [
      {label:'选择济州机场', detail:'济州国际机场(RKPC)是韩国最繁忙的机场之一。', voice:'选择济州机场。'},
      {label:'放置Cessna 172', detail:'世界上使用最广泛的训练飞机。', voice:'放置Cessna 172。'},
      {label:'移至跑道07', detail:'跑道07表示方向73度（东），济州机场主跑道。', voice:'移至跑道07。'},
      {label:'确认天气（晴）', detail:'济州有些风但适合飞行！', voice:'确认天气。'},
      {label:'主电池开', detail:'给飞机通电。', voice:'主电池开。'},
      {label:'航电设备开', detail:'打开航电设备。', voice:'航电设备开。'},
      {label:'信标灯开', detail:'打开红色旋转灯。', voice:'信标灯开。'},
      {label:'启动发动机', detail:'螺旋桨开始转动！', voice:'启动发动机。'},
      {label:'NAV/频闪灯开', detail:'打开导航灯。', voice:'导航灯开。'},
      {label:'襟翼10°', detail:'展开襟翼准备起飞。', voice:'襟翼10度。'},
      {label:'松开驻机刹车', detail:'松开刹车。', voice:'松开刹车。'},
      {label:'准备起飞！', detail:'一切就绪！飞向美丽的济州天空！', voice:'准备起飞！'},
    ],
  },
};
